# -*- coding: utf-8 -*-
"""Rodriggo Marcelino Santos - resposta_atividade_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WVxYQ3Ul7YoVdry8nMgBPOuAngN4Fsc5

**Inserir aqui o nome dos integrantes do grupo:**
Rodriggo Marcelino Santos
---
"""

!pip install sweetviz
import sweetviz as sv
import pandas as pd
from google.colab import files
import io

dados_car = pd.read_csv('car_crashes.csv',sep=',')
dados_flights = pd.read_csv('flights.csv',sep=',')
dados_planets = pd.read_csv('planets.csv',sep=',')

"""Aplicação com os dados de dados_car"""

dados_car.keys()

relatorio = sv.analyze(dados_car)
relatorio.show_notebook(w="100%",h="full")

relatorio = sv.compare([dados_car[dados_car['abbrev']=='CA'],"CA"],[dados_car[dados_car['abbrev']=='LA'],"LA"])
relatorio.show_notebook(w="100%",h="full")

relatorio = sv.compare_intra(dados_car, dados_car["abbrev"]=="NY",["NY", "Others"])
relatorio.show_notebook(w="100%",h="full")

"""Aplicação com os dados de dados_flights"""

dados_flights.keys()

relatorio = sv.analyze(dados_flights)
relatorio.show_notebook(w="100%",h="full")

relatorio = sv.compare([dados_flights[dados_flights['month']=='July'],'July'],[dados_flights[dados_flights['month']=='January'],'January'])
relatorio.show_notebook(w="100%",h="full")

relatorio = sv.compare_intra(dados_flights, dados_flights["month"] == "December",["December", "Others"])
relatorio.show_notebook(w="100%",h="full")

"""Aplicação com os dados de dados_planets"""

dados_planets.keys()

relatorio = sv.analyze(dados_planets)
relatorio.show_notebook(w="100%",h="full")

relatorio = sv.compare([dados_planets[dados_planets['method']=='Transit'],"Transit"],[dados_planets[dados_planets['method']=='Radial Velocity'],"Radial Velocity"])
relatorio.show_notebook(w="100%",h="full")

relatorio = sv.compare_intra(dados_planets, dados_planets['method']=="Eclipse Timing Variations",["Eclipse Timing Variations", "Others"])
relatorio.show_notebook(w="100%",h="full")