# -*- coding: utf-8 -*-
"""rodriggo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1od92o2tm38c0dOy5pg0dm5QCnqYp81no
"""

#importando as bibliotecas necessárias
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import random
import numpy as np
import plotly 
import plotly.offline as py
import plotly.graph_objs as go # criará de fato os gráficos
from plotly.offline import plot, iplot
import cufflinks as cf # para conectar o plotly ao pandas
cf.go_offline()
plotly.offline.init_notebook_mode(connected = True)
import plotly.io as pio
pio.renderers.default = 'colab'

#dados do exemplo 1
valores= 10*np.random.randn(50,4)
dados_1 = pd.DataFrame(valores, columns=['TIPO 1','TIPO 2','TIPO 3','TIPO 4'])
dados_1.head()

dados_1.iplot(kind='scatter', x='TIPO 1',y='TIPO 2', mode='markers',color='darkblue')

dados_1.iplot(kind='scatter', x='TIPO 1',y='TIPO 2', mode='markers',color='darkblue')

# gerando os dados
tipos = ['TIPO 1', 'TIPO 2', 'TIPO 3', 'TIPO 4']
antes = [75, 69, 29, 73]
depois = [50, 70, 20, 27]

# configurações
antes = go.Bar(x = tipos, y = antes, name = 'Antes',marker = {'color': 'blue'})
depois = go.Bar(x = tipos, y = depois, name = 'Depois',marker = {'color': 'red'})
##gerando o gráfico
dados_3 = [antes, depois]
py.iplot(dados_3)

