# -*- coding: utf-8 -*-
"""rodriggo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1od92o2tm38c0dOy5pg0dm5QCnqYp81no
"""

#importando as bibliotecas necessárias
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import random
import numpy as np
import plotly 
import plotly.offline as py
import plotly.graph_objs as go # criará de fato os gráficos
from plotly.offline import plot, iplot
import cufflinks as cf # para conectar o plotly ao pandas
cf.go_offline()
plotly.offline.init_notebook_mode(connected = True)
import plotly.io as pio
pio.renderers.default = 'colab'

#dados
dados = pd.read_excel('dados_mapa_1.xlsx')
cidade = dados['Cidade']
estado = dados['Estado']
latitude= dados['latitude_']
longitude = dados['longitude_']
vendas = dados['Vendas']
#criando um dicionario
colunas={'CIDADE':cidade,'ESTADO':estado,'LATITUDE':latitude,'LONGITUDE':longitude,'Vendas':vendas}
tabela_dados = pd.DataFrame(colunas)
tabela_dados

fig = px.density_mapbox(tabela_dados, 
                        lat='LATITUDE', 
                        lon='LONGITUDE', 
                        z='Vendas', 
                        radius=30,
                        center=dict(lat=-23.70, lon=-46.55), 
                        zoom=7,
                        mapbox_style="stamen-terrain")
fig.show()